spring:  
  application:
    name: client-service
    
---
spring:
  profiles: zone1
server:
  port: ${PORT:8081}
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/     

---
spring:
  profiles: zone2
server:
  port: ${PORT:8082}
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8762/eureka/,http://localhost:8761/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: zone3
server:
  port: ${PORT:8083}
eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8763/eureka/,http://localhost:8761/eureka/,http://localhost:8762/eureka/