spring:  
  application:
    name: discovery-service
    
---
spring:
  profiles: peer1
server:  
  port: ${PORT:8761}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    hostname: localhost
    metadataMap:
      zone: zone1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

---
spring:
  profiles: peer2
server:  
  port: ${PORT:8762}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    hostname: peer2
    metadataMap:
      zone: zone2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
  
---
spring:
  profiles: peer3
server:  
  port: ${PORT:8763}
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    hostname: peer3
    metadataMap:
      zone: zone3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
